### ISSUE TITLE
[BUG] F-Droid can't build

### ISSUE THREAD

**Issue by licaon-kter** [samolego/Canta#49]
https://monitor.f-droid.org/builds/log/org.samo_lego.canta/91#site-footer

but the other two arches were built fine...and repro

diff log for 91: [canta91.log](https://github.com/samolego/Canta/files/14801953/canta91.log)

/LE: fyi https://gitlab.com/fdroid/fdroiddata/-/commit/7acc22457ac29f839f157509bb48ee440fcf6356

**Comment by samolego** [comment]
Thanks for reporting, that's strange :/ ... I'll need to take a look.

**Comment by licaon-kter** [comment]
trying to update to the new non-Flutter codebase
```
  - versionName: 2.1.0
    versionCode: 202
    commit: 77e2864e0083f1c692eb3d95e3801c8838b6c8e8
    subdir: app
    gradle:
      - yes
    binary: https://github.com/samolego/Canta/releases/download/%v/app-release.apk

AllowedAPKSigningKeys: 0a2640317c43272188c3e13194c15460691f12c39ea19bba727dd67fb56289d4

AutoUpdateMode: Version
UpdateCheckMode: Tags
UpdateCheckData: app/gradle.properties|version_code=(\d+)|.|version_name="(.*)"
CurrentVersion: 2.1.0
CurrentVersionCode: 202
```


but...
```
 ERROR: Could not build app org.samo_lego.canta: Unexpected version/version code in output; APK: '"2.1.0"' / '202',  Expected: '2.1.0' / '202'
```
because for some reason.. the versionName in the APK is literally `"2.1.0"` yes quotes included per https://github.com/samolego/Canta/blob/2.1.0/app/gradle.properties#L3

was this intentional?
